### ISSUE TITLE
Css background values with vendor prefixes

### ISSUE THREAD

**Issue by joshuaboshi** [Box9/jss#33]
Hello,

I wanted to use JSS to generate CSS rule like this:

``` css
body.mystyle {
    background-image: -moz-linear-gradient(top, rgba(0,0,0,0) 75%, rgba(0,0,0,0.65));
    background-image: -webkit-linear-gradient(top, rgba(0,0,0,0) 75%, rgba(0,0,0,0.65));
    background-image: -o-linear-gradient(top, rgba(0,0,0,0) 75%, rgba(0,0,0,0.65));
    background-image: -ms-linear-gradient(top, rgba(0,0,0,0) 75%, rgba(0,0,0,0.65));
    background-image: linear-gradient(top, rgba(0,0,0,0) 75%, rgba(0,0,0,0.65));
}
```

The API of JSS is great. But usage of Objects for css properties will not work in case like above.
Maybe there could be a new `set` method which will accept strings directly?

I would like to avoid browser detection and setting just the correct rule.

Thanks!
